/*
 * This file is generated by tool/generate_ast.py
 */

namespace cslox
{
    abstract class Expr
    {
        internal interface IVisitor<R>
        {
            R VisitAssignExpr(Assign expr);
            R VisitBinaryExpr(Binary expr);
            R VisitCallExpr(Call expr);
            R VisitGetExpr(Get expr);
            R VisitLambdaExpr(Lambda expr);
            R VisitTernaryExpr(Ternary expr);
            R VisitGroupingExpr(Grouping expr);
            R VisitLiteralExpr(Literal expr);
            R VisitLogicalExpr(Logical expr);
            R VisitSetExpr(Set expr);
            R VisitThisExpr(This expr);
            R VisitUnaryExpr(Unary expr);
            R VisitVariableExpr(Variable expr);
        }

        internal class Assign : Expr
        {
            internal Assign(Token name, Expr value)
            {
                this.name = name;
                this.value = value;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitAssignExpr(this);
            }

            internal readonly Token name;
            internal readonly Expr value;
        }

        internal class Binary : Expr
        {
            internal Binary(Expr left, Token @operator, Expr right)
            {
                this.left = left;
                this.@operator = @operator;
                this.right = right;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitBinaryExpr(this);
            }

            internal readonly Expr left;
            internal readonly Token @operator;
            internal readonly Expr right;
        }

        internal class Call : Expr
        {
            internal Call(Expr callee, Token paren, List<Expr> arguments)
            {
                this.callee = callee;
                this.paren = paren;
                this.arguments = arguments;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitCallExpr(this);
            }

            internal readonly Expr callee;
            internal readonly Token paren;
            internal readonly List<Expr> arguments;
        }

        internal class Get : Expr
        {
            internal Get(Expr @object, Token name)
            {
                this.@object = @object;
                this.name = name;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitGetExpr(this);
            }

            internal readonly Expr @object;
            internal readonly Token name;
        }

        internal class Lambda : Expr
        {
            internal Lambda(List<Token> @params, List<Stmt> body)
            {
                this.@params = @params;
                this.body = body;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitLambdaExpr(this);
            }

            internal readonly List<Token> @params;
            internal readonly List<Stmt> body;
        }

        internal class Ternary : Expr
        {
            internal Ternary(Expr test, Expr consequent, Expr alternate)
            {
                this.test = test;
                this.consequent = consequent;
                this.alternate = alternate;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitTernaryExpr(this);
            }

            internal readonly Expr test;
            internal readonly Expr consequent;
            internal readonly Expr alternate;
        }

        internal class Grouping : Expr
        {
            internal Grouping(Expr expression)
            {
                this.expression = expression;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitGroupingExpr(this);
            }

            internal readonly Expr expression;
        }

        internal class Literal : Expr
        {
            internal Literal(object? value)
            {
                this.value = value;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitLiteralExpr(this);
            }

            internal readonly object? value;
        }

        internal class Logical : Expr
        {
            internal Logical(Expr left, Token @operator, Expr right)
            {
                this.left = left;
                this.@operator = @operator;
                this.right = right;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitLogicalExpr(this);
            }

            internal readonly Expr left;
            internal readonly Token @operator;
            internal readonly Expr right;
        }

        internal class Set : Expr
        {
            internal Set(Expr @object, Token name, Expr value)
            {
                this.@object = @object;
                this.name = name;
                this.value = value;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitSetExpr(this);
            }

            internal readonly Expr @object;
            internal readonly Token name;
            internal readonly Expr value;
        }

        internal class This : Expr
        {
            internal This(Token keyword)
            {
                this.keyword = keyword;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitThisExpr(this);
            }

            internal readonly Token keyword;
        }

        internal class Unary : Expr
        {
            internal Unary(Token @operator, Expr right)
            {
                this.@operator = @operator;
                this.right = right;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitUnaryExpr(this);
            }

            internal readonly Token @operator;
            internal readonly Expr right;
        }

        internal class Variable : Expr
        {
            internal Variable(Token name)
            {
                this.name = name;
            }

            internal override R Accept<R>(IVisitor<R> visitor)
            {
                return visitor.VisitVariableExpr(this);
            }

            internal readonly Token name;
        }

        internal abstract R Accept<R>(IVisitor<R> visitor);
    }
}
