/*
 * This file is generated by tool/generate_ast.py
 */

namespace cslox
{
    abstract class Stmt
    {
        internal interface IVisitor
        {
            void VisitBlockStmt(Block stmt);
            void VisitExpressionStmt(Expression stmt);
            void VisitPrintStmt(Print stmt);
            void VisitVarStmt(Var stmt);
        }

        internal class Block : Stmt
        {
            internal Block(List<Stmt> statements)
            {
                this.statements = statements;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitBlockStmt(this);
            }

            internal readonly List<Stmt> statements;
        }

        internal class Expression : Stmt
        {
            internal Expression(Expr expression)
            {
                this.expression = expression;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitExpressionStmt(this);
            }

            internal readonly Expr expression;
        }

        internal class Print : Stmt
        {
            internal Print(Expr expression)
            {
                this.expression = expression;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitPrintStmt(this);
            }

            internal readonly Expr expression;
        }

        internal class Var : Stmt
        {
            internal Var(Token name, Expr? initializer)
            {
                this.name = name;
                this.initializer = initializer;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitVarStmt(this);
            }

            internal readonly Token name;
            internal readonly Expr? initializer;
        }

        internal abstract void Accept(IVisitor visitor);
    }
}
