/*
 * This file is generated by tool/generate_ast.py
 */

namespace cslox
{
    abstract class Stmt
    {
        internal interface IVisitor
        {
            void VisitBlockStmt(Block stmt);
            void VisitExpressionStmt(Expression stmt);
            void VisitFunctionStmt(Function stmt);
            void VisitIfStmt(If stmt);
            void VisitPrintStmt(Print stmt);
            void VisitReturnStmt(Return stmt);
            void VisitVarStmt(Var stmt);
            void VisitWhileStmt(While stmt);
            void VisitBreakStmt(Break stmt);
            void VisitContinueStmt(Continue stmt);
        }

        internal class Block : Stmt
        {
            internal Block(List<Stmt> statements)
            {
                this.statements = statements;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitBlockStmt(this);
            }

            internal readonly List<Stmt> statements;
        }

        internal class Expression : Stmt
        {
            internal Expression(Expr expression)
            {
                this.expression = expression;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitExpressionStmt(this);
            }

            internal readonly Expr expression;
        }

        internal class Function : Stmt
        {
            internal Function(Token name, List<Token> @params, List<Stmt> body)
            {
                this.name = name;
                this.@params = @params;
                this.body = body;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitFunctionStmt(this);
            }

            internal readonly Token name;
            internal readonly List<Token> @params;
            internal readonly List<Stmt> body;
        }

        internal class If : Stmt
        {
            internal If(Expr condition, Stmt thenBranch, Stmt? elseBranch)
            {
                this.condition = condition;
                this.thenBranch = thenBranch;
                this.elseBranch = elseBranch;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitIfStmt(this);
            }

            internal readonly Expr condition;
            internal readonly Stmt thenBranch;
            internal readonly Stmt? elseBranch;
        }

        internal class Print : Stmt
        {
            internal Print(Expr expression)
            {
                this.expression = expression;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitPrintStmt(this);
            }

            internal readonly Expr expression;
        }

        internal class Return : Stmt
        {
            internal Return(Token keyword, Expr? value)
            {
                this.keyword = keyword;
                this.value = value;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitReturnStmt(this);
            }

            internal readonly Token keyword;
            internal readonly Expr? value;
        }

        internal class Var : Stmt
        {
            internal Var(Token name, Expr? initializer)
            {
                this.name = name;
                this.initializer = initializer;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitVarStmt(this);
            }

            internal readonly Token name;
            internal readonly Expr? initializer;
        }

        internal class While : Stmt
        {
            internal While(Expr condition, Stmt body)
            {
                this.condition = condition;
                this.body = body;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitWhileStmt(this);
            }

            internal readonly Expr condition;
            internal readonly Stmt body;
        }

        internal class Break : Stmt
        {
            internal Break(Token keyword)
            {
                this.keyword = keyword;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitBreakStmt(this);
            }

            internal readonly Token keyword;
        }

        internal class Continue : Stmt
        {
            internal Continue(Token keyword)
            {
                this.keyword = keyword;
            }

            internal override void Accept(IVisitor visitor)
            {
                visitor.VisitContinueStmt(this);
            }

            internal readonly Token keyword;
        }

        internal abstract void Accept(IVisitor visitor);
    }
}
