# -*- coding: utf-8 -*-
# author: Tac
# contact: cookiezhx@163.com

"""
https://craftinginterpreters.com/representing-code.html#metaprogramming-the-trees
Chapter 5.2.2
"""

from __future__ import absolute_import, division, print_function
import sys
import os
import io
try:
    from typing import TYPE_CHECKING
except ImportError:
    TYPE_CHECKING = False

if TYPE_CHECKING:
    from typing import Iterable


def main():
    # type: () -> None
    """Generate src/cslox/Expr.cs"""
    if len(sys.argv) >= 2:
        output_dir = sys.argv[1]
        if not os.path.isdir(output_dir):
            print("[Error] Ouput directory '" + output_dir + "' doesn't exist.", file=sys.stderr)
            sys.exit(64)
        output_dir = os.path.normpath(output_dir)
    else:
        output_dir = os.path.normpath(os.path.join(__file__, "..", "..", "src", "cslox"))

    _define_ast(output_dir, "Expr", [
        "Binary   : Expr left, Token @operator, Expr right",
        "Grouping : Expr expression",
        "Literal  : object? value",
        "Unary    : Token @operator, Expr right"
    ])


def _define_ast(output_dir, base_name, types):
    # type: (str, str, Iterable[str]) -> None
    path = os.path.join(output_dir, base_name + ".cs")
    with io.open(path, "w", encoding="utf-8") as fp:
        print("/*", file=fp)
        print(" * This file is generated by tool/generate_ast.py", file=fp)
        print(" */", file=fp)
        print(file=fp)
        print("namespace cslox", file=fp)
        print("{", file=fp)
        print("    abstract class " + base_name, file=fp)
        print("    {", file=fp)

        _define_visitor(fp, base_name, types)

        # The AST classes.
        for type_info in types:
            class_name, _, fields = type_info.partition(":")
            class_name = class_name.strip()
            fields = fields.strip()
            _define_type(fp, base_name, class_name, fields)
            print(file=fp)

        # Tye base accept() method.
        print("        internal abstract R Accept<R>(IVisitor<R> visitor);", file=fp)

        print("    }", file=fp)
        print("}", file=fp)


def _define_type(fp, base_name, class_name, field_list):
    # type: (io.TextIOBase, str, str, str) -> None
    print("        internal class " + class_name + " : " + base_name, file=fp)
    print("        {", file=fp)

    # Contructor.
    print("            internal " + class_name + "(" + field_list + ")", file=fp)
    print("            {", file=fp)

    # Store parameters in fields.
    fields = field_list.split(", ")
    for field in fields:
        name = field.rpartition(" ")[-1]
        print("                this." + name + " = " + name + ";", file=fp)

    print("            }", file=fp)

    # Visitor pattern.
    print(file=fp)
    print("            internal override R Accept<R>(IVisitor<R> visitor)", file=fp)
    print("            {", file=fp)
    print("                return visitor.Visit" + class_name + base_name + "(this);", file=fp)
    print("            }", file=fp)

    # Fields.
    print(file=fp)
    for field in fields:
        print("            internal readonly " + field + ";", file=fp)

    print("        }", file=fp)


def _define_visitor(fp, base_name, types):
    # type: (io.TextIOBase, str, Iterable[str]) -> None
    print("        internal interface IVisitor<R>", file=fp)
    print("        {", file=fp)

    for type_info in types:
        type_name = type_info.partition(":")[0].strip()
        print("            R Visit" + type_name + base_name + "(" +
              type_name + " " + base_name.lower() + ");", file=fp)

    print("        }", file=fp)
    print(file=fp)


if __name__ == "__main__":
    main()
